// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byrcgldjjhjknvkewxxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5cmNnbGRqamhqa252a2V3eHhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTcyMTksImV4cCI6MjA2OTAzMzIxOX0.9aWY3-ld31F5V1WWXzlqT49HEI5DD-E61dJ3Wozvvfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});